version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'dev'

  - package-ecosystem: 'npm'
    directory: '/sdk/js'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'dev'
