project_name: lorawan-stack

builds:
  - main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

  - main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archive:
  files:
    - LICENSE
    - README.md
    - doc/**/*
    - docker-compose.yml
    - public/**/*
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip

changelog:
  skip: true

release:
  prerelease: auto

nfpm:
  vendor: The Things Network
  homepage: https://www.thethingsnetwork.org
  maintainer: The Things Network Foundation <stack@thethingsnetwork.org>
  description: The Things Network Stack for LoRaWAN
  license: Apache 2.0
  formats:
    - deb
    - rpm
  recommends:
    - redis
    - cockroach
  files:
    "public/**/*": "/srv/ttn-lorawan/public"

snapcraft:
  name: ttn-lw-stack
  summary: The Things Network Stack for LoRaWAN
  description: The Things Network Stack for LoRaWAN
  grade: stable
  confinement: strict
  publish: true
  apps:
    ttn-lw-stack:
      plugs: [ home, network, network-bind ]
    ttn-lw-cli:
      plugs: [ home, network, network-bind ]

# TODO: Generate separate formulas for stack+CLI and CLI only.(https://github.com/TheThingsNetwork/lorawan-stack/issues/108)
brew:
  name: ttn-lw-stack
  github:
    owner: TheThingsNetwork
    name: homebrew-lorawan-stack
  commit_author:
    name: ttn-ci
    email: stack@thethingsnetwork.org
  homepage: https://www.thethingsnetwork.org
  description: The Things Network Stack for LoRaWAN
  skip_upload: auto
  install: |
    bin.install "ttn-lw-cli"
    libexec.install %w[ttn-lw-stack public doc]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"ttn-lw-stack").write_env_script libexec/"ttn-lw-stack", env

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - ttn-lw-cli
      - ttn-lw-stack
    image_templates:
      - "thethingsnetwork/lorawan-stack:latest"
      - "thethingsnetwork/lorawan-stack:{{ .Major }}"
      - "thethingsnetwork/lorawan-stack:{{ .Major }}.{{ .Minor }}"
      - "thethingsnetwork/lorawan-stack:{{ .Version }}"
    skip_push: auto
    extra_files:
      - public
