project_name: lorawan-stack

changelog:
  skip: true

release:
  prerelease: auto

builds:
  - id: stack
    main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

  - id: cli
    main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - id: stack
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
      - stack
    files:
      - LICENSE
      - README.md
      - doc/**/*
      - docker-compose.yml
      - public/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: cli
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
    files:
      - LICENSE
      - README.md
      - doc/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: stack
    builds:
      - cli
      - stack
    vendor: The Things Network
    homepage: https://www.thethingsnetwork.org
    maintainer: The Things Network Foundation <stack@thethingsnetwork.org>
    description: The Things Stack for LoRaWAN
    license: Apache 2.0
    formats:
      - deb
      - rpm
    recommends:
      - redis
      - cockroach
    files:
      "public/**/*": "/srv/ttn-lorawan/public"

snapcrafts:
  - id: stack
    builds:
      - cli
      - stack
    name: ttn-lw-stack
    summary: The Things Stack for LoRaWAN
    description: The Things Stack for LoRaWAN
    grade: stable
    confinement: strict
    publish: true
    apps:
      ttn-lw-stack:
        plugs: [ home, network, network-bind ]
      ttn-lw-cli:
        plugs: [ home, network, network-bind ]

brews:
  - name: ttn-lw-stack
    ids:
      - stack
    github:
      owner: TheThingsNetwork
      name: homebrew-lorawan-stack
    commit_author:
      name: ttn-ci
      email: stack@thethingsnetwork.org
    homepage: https://www.thethingsnetwork.org
    description: The Things Stack for LoRaWAN
    conflicts:
      - ttn-lw-cli
    skip_upload: auto
    install: |
      bin.install "ttn-lw-cli"
      libexec.install %w[ttn-lw-stack public doc]
      env = {
          :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
      }
      (bin/"ttn-lw-stack").write_env_script libexec/"ttn-lw-stack", env

  - name: ttn-lw-cli
    ids:
      - cli
    github:
      owner: TheThingsNetwork
      name: homebrew-lorawan-stack
    commit_author:
      name: ttn-ci
      email: stack@thethingsnetwork.org
    homepage: https://www.thethingsnetwork.org
    description: CLI of The Things Stack for LoRaWAN
    conflicts:
      - ttn-lw-stack
    skip_upload: auto
    install: |
      bin.install "ttn-lw-cli"
      libexec.install doc

blobs:
  - provider: s3
    # NOTE: GoReleaser documentation says that bucket is a template, but it's not.
    bucket: the-things-stack-releases
    ids:
    - stack
    - cli
    folder: "{{ .Version }}"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - ttn-lw-cli
      - ttn-lw-stack
    image_templates:
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:latest'
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:{{ .Major }}'
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:{{ .Major }}.{{ .Minor }}'
      - '{{ or (index .Env "DOCKER_IMAGE") "lorawan-stack" }}:{{ .Version }}'
    skip_push: auto
    extra_files:
      - public
