project_name: lorawan-stack

changelog:
  skip: true

release:
  disable: true

builds:
  - id: stack
    main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
    ldflags:
      - -s
      - -w
      - -X go.thethings.network/lorawan-stack/v3/pkg/version.BuildDate={{.Date}}
      - -X go.thethings.network/lorawan-stack/v3/pkg/version.GitCommit={{.ShortCommit}}
      - -X go.thethings.network/lorawan-stack/v3/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

  - id: cli
    main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
    ldflags:
      - -s
      - -w
      - -X go.thethings.network/lorawan-stack/v3/pkg/version.BuildDate={{.Date}}
      - -X go.thethings.network/lorawan-stack/v3/pkg/version.GitCommit={{.ShortCommit}}
      - -X go.thethings.network/lorawan-stack/v3/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    binaries:
      - ttn-lw-cli
      - ttn-lw-stack
    image_templates:
      - 'lorawan-stack-dev:{{ .FullCommit }}'
    skip_push: true
    extra_files:
      - public
