language: go
go:
- 1.9
go_import_path: github.com/TheThingsNetwork/ttn
sudo: required
services:
- docker
cache:
  directories:
  - $GOPATH/bin
  - $GOPATH/pkg
  - $GOPATH/src/github.com/golang # dep
  - $GOPATH/src/github.com/alecthomas # gometalinter
  - $GOPATH/src/github.com/dgrijalva # jwt-go
install:
- make dev-deps
- make deps
- go get -u github.com/dgrijalva/jwt-go
before_script:
- docker run -d -p 127.0.0.1:6379:6379 redis
- docker run -d -p 127.0.0.1:26257:26257 cockroachdb/cockroach:v1.1.3 start --insecure
script:
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make go.protos.clean go.protos; fi # only on pull requests
- make go.misspell
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make go.unconvert; fi # only on pull requests
- make go.fmt
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make go.lint-travis-comment --no-print-directory; fi # only on pull requests
- make headers.check
- git diff --exit-code
- GOARCH=amd64 make test
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then GOARCH=386 make test; fi # only on pull requests
before_install:
- openssl aes-256-cbc -K $encrypted_29695605fa9e_key -iv $encrypted_29695605fa9e_iv -in github.pem.enc -out .make/github.pem -d
