language: go
go:
- "1.10"
go_import_path: go.thethings.network/lorawan-stack
sudo: required
services:
- docker
cache:
  directories:
  - $GOPATH/bin
  - $GOPATH/pkg
  - $GOPATH/src/github.com/golang # dep
  - $GOPATH/src/github.com/alecthomas # gometalinter
  - $GOPATH/src/github.com/mattn # goveralls
install:
- make dev-deps
- make deps
- make dev.certs
before_script:
- make dev.databases.start
script:
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make go.protos.clean go.protos; fi # only on pull requests
- make go.misspell
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make go.unconvert; fi # only on pull requests
- make go.fmt
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make go.lint-travis || true; fi # only on pull requests
- make headers.check
- make dev.git-diff
- GOARCH=amd64 TEST_SLOWDOWN=16 make test
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then GOARCH=386 TEST_SLOWDOWN=16 make test; fi # only on pull requests
- if [[ $TRAVIS_EVENT_TYPE != "push" ]]; then make build-all; fi # only on pull requests
- make js.lint
- make js.test
- make js.vulnerabilities
after_success:
- make go.coveralls
