sudo: required
conditions: v1
if: type = pull_request OR branch = master OR tag IS present
os: linux
git:
  depth: false
language: go
go: 1.14.x
go_import_path: go.thethings.network/lorawan-stack
env:
  global:
    - GOPROXY=https://proxy.golang.org
    - NODE_ENV=production
    - YARN_CACHE_FOLDER=$HOME/.cache/yarn
    - MAGE=$HOME/.cache/mage/mage
    - TEST_SLOWDOWN=8
    - TEST_REDIS=1
    - PATH=/snap/bin:$PATH
    - HUGO_BASE_URL=https://thethingsstack.io/
    - DOCKER_IMAGE=thethingsnetwork/lorawan-stack
    - DOCKER_IMAGE_DEV=thethingsnetwork/lorawan-stack-dev
matrix:
  include:
    - env: RUNTYPE=js
    - env: RUNTYPE=release
      if: tag IS present OR (type != pull_request AND branch = master)
services:
  - docker
cache:
  directories:
    - '$GOPATH/pkg/mod'
    - '$HOME/.cache/go-build'
    - '$HOME/.cache/mage'
    - '$HOME/.cache/yarn'
before_install:
  - |
    if [[ "$TRAVIS_EVENT_TYPE" == "push" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
      set -e
      go clean -modcache
      go clean -cache
      rm -rf $HOME/.cache/mage/*
      rm -rf $HOME/.cache/yarn/*
    fi
  - |
    if [[ ! -z "$encrypted_fc3d5d829302_key" ]]; then
      openssl aes-256-cbc -K $encrypted_fc3d5d829302_key \
                          -iv $encrypted_fc3d5d829302_iv \
                          -in pkg/blob/testdata/gcloud.json.enc \
                          -out pkg/blob/testdata/gcloud.json \
                          -d
    fi
  - |
    if [[ "$RUNTYPE" == "release" ]]; then
      echo "$SNAPCRAFT_LOGIN_ENCRYPTION_PASS" | gpg --passphrase-fd 0 snapcraft.login.gpg
      nvm install 10.16.0
    fi
  - |
    if [[ "$RUNTYPE" == "js" ]]; then
      nvm install 10.16.0
    fi
install:
  - make init
  - |
    if [[ "$RUNTYPE" == "js" ]]; then
      $MAGE js:deps jsSDK:deps
    fi
  - |
    if [[ "$RUNTYPE" == "release" ]]; then
      set -e
      sudo apt-get -y update
      sudo apt-get install -y rpm snapd
      sudo snap install snapcraft --classic
      $MAGE jsSDK:deps js:deps
      $MAGE docs:deps
    fi
script:
  - if [[ "$RUNTYPE" == "js" ]]; then $MAGE jsSDK:clean jsSDK:build; fi
  - if [[ "$RUNTYPE" == "js" ]]; then $MAGE js:translations; fi
  - if [[ "$RUNTYPE" == "js" ]]; then $MAGE js:backendTranslations; fi
  - if [[ "$RUNTYPE" == "js" ]]; then $MAGE js:test jsSDK:test; fi
  - if [[ "$RUNTYPE" == "js" ]]; then $MAGE js:lint jsSDK:lint; fi
  - if [[ "$RUNTYPE" == "release" ]]; then $MAGE version:files; fi
  - $MAGE git:diff
after_success:
  - |
    if [[ "$RUNTYPE" == "release" ]]; then
      set -e
      rm -rf doc/public
      mkdir doc/public
      git fetch
      git --work-tree=doc/public checkout origin/gh-pages -- .
      git reset -- .
    fi
  - |
    if [[ "$RUNTYPE" == "release" ]]; then
      set -e
      $MAGE js:build
      $MAGE docs:build
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      snapcraft login --with snapcraft.login
      if [[ ! -z "$TRAVIS_TAG" && "$TRAVIS_TAG" =~ ^v3\.[0-9]+\.[0-9]+ ]]; then
        cd tools && GO111MODULE=on go run github.com/goreleaser/goreleaser --release-notes <(printf "[Release notes](https://github.com/TheThingsNetwork/lorawan-stack/blob/${TRAVIS_TAG}/CHANGELOG.md#$(echo ${TRAVIS_TAG} | sed "s/v\([1-9]\+\)\.\([1-9]\+\)\.\([1-9]\+\)/\1\2\3---$(date +%Y-%m-%d)/"))")
      else
        cd tools && GO111MODULE=on go run github.com/goreleaser/goreleaser --snapshot
        docker push $DOCKER_IMAGE_DEV:$TRAVIS_COMMIT
      fi
    fi
deploy:
  - provider: pages
    local_dir: doc/public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    fqdn: thethingsstack.io
    on:
      tags: true
      condition: $RUNTYPE = "release"
