sudo: required
conditions: v1
if: type = pull_request OR branch = master OR tag IS present
os: linux
language: go
go: 1.12.x
go_import_path: go.thethings.network/lorawan-stack
env:
  global:
  - YARN_CACHE_FOLDER=$HOME/.cache/yarn
  - MAGE=$HOME/.cache/mage/mage
  - TEST_SLOWDOWN=8
  - TEST_REDIS=1
  - PATH=/snap/bin:$PATH
matrix:
  include:
  - env: RUNTYPE=js
  - env: RUNTYPE=go.test RUN_GOARCH=amd64
  - env: RUNTYPE=go.test RUN_GOARCH=386
  - env: RUNTYPE=go.lint
  - env: RUNTYPE=release
    if: tag IS present OR (type != pull_request AND branch = master)
services:
- docker
cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"
  - "$HOME/.cache/mage"
  - "$HOME/.cache/yarn"
before_install:
- |
  if [[ "$TRAVIS_EVENT_TYPE" == "push" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    go clean -modcache
    go clean -cache
    rm -rf $HOME/.cache/mage/*
    rm -rf $HOME/.cache/yarn/*
  fi
- |
  if [[ ! -z "$encrypted_fc3d5d829302_key" ]]; then
    openssl aes-256-cbc -K $encrypted_fc3d5d829302_key \
                        -iv $encrypted_fc3d5d829302_iv \
                        -in pkg/blob/testdata/gcloud.json.enc \
                        -out pkg/blob/testdata/gcloud.json \
                        -d
  fi
- |
  if [[ "$RUNTYPE" == "go.test" ]]; then
    sudo rm /usr/local/bin/docker-compose
    curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin
  fi
- |
  if [[ "$RUNTYPE" == "release" ]]; then
    openssl aes-256-cbc -K $encrypted_82ec1379e985_key -iv $encrypted_82ec1379e985_iv -in snapcraft.login.enc -out snapcraft.login -d
  fi
install:
- |
  if [[ "$RUNTYPE" =~ go. ]]; then
    make go.deps
  fi
- |
  if [[ "$RUNTYPE" == "js" ]]; then
    make js.dev-deps js.deps sdk.js.deps
  fi
- |
  if [[ "$RUNTYPE" == "release" ]]; then
    sudo apt-get -y update
    sudo apt-get install -y rpm snapd
    sudo snap install snapcraft --classic
    make deps
  fi
before_script:
- |
  if [[ "$RUNTYPE" == "go.test" ]]; then
    make dev.databases.start
    make dev.certs
  fi
script:
- if [[ "$RUNTYPE" == "js" ]]; then make js.translations; fi
- if [[ "$RUNTYPE" == "js" ]]; then make js.test sdk.js.test; fi
- if [[ "$RUNTYPE" == "js" ]]; then make js.lint; fi
- if [[ "$RUNTYPE" == "js" ]]; then make proto.sdk.js.clean proto.sdk.js sdk.js.build; fi
- if [[ "$RUNTYPE" == "js" ]]; then make proto.swagger.clean proto.swagger; fi
- if [[ "$RUNTYPE" == "js" ]]; then make proto.markdown.clean proto.markdown; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make headers.check; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make proto.go.clean proto.go; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make messages; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make go.lint; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make go.unconvert; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make go.fmt; fi
- if [[ "$RUNTYPE" == "go.lint" ]]; then make go.misspell; fi
- |
  if [[ "$RUNTYPE" == "go.test" ]]; then
    if [[ "$RUN_GOARCH" == "amd64" ]]; then
      GOARCH=$RUN_GOARCH make go.coveralls
    else
      GOARCH=$RUN_GOARCH make go.test
    fi
  fi
- if [[ "$RUNTYPE" == "go.test" ]]; then go run ./cmd/ttn-lw-stack version; fi
- if [[ "$RUNTYPE" == "go.test" ]]; then go run ./cmd/ttn-lw-cli version; fi
- if [[ "$RUNTYPE" == "release" ]]; then $MAGE version:files; fi
- make git.diff
after_success:
- |
  if [[ "$RUNTYPE" == "release" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    snapcraft login --with snapcraft.login
  fi
deploy:
- provider: script
  skip_cleanup: true
  script: GO111MODULE=on go run github.com/goreleaser/goreleaser
  on:
    tags: true
    condition: $RUNTYPE = "release"
- provider: script
  skip_cleanup: true
  script: GO111MODULE=on go run github.com/goreleaser/goreleaser --snapshot
  on:
    branch: master
    condition: $RUNTYPE = "release"
