
[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/gogo/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/grpc-gateway"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/smartystreets/assertions"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.0"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "github.com/robertkrimen/otto"
  source = "github.com/johanstokking/otto"

[[constraint]]
  name = "github.com/TheThingsNetwork/go-cayenne-lib"
  version = "1.0.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.13.0"
