required = ["github.com/golang/dep"]

[[constraint]]
  name = "github.com/RangelReale/osin"
  version = "1.0.1"

[[constraint]]
  name = "github.com/TheThingsNetwork/go-cayenne-lib"
  version = "1.0.0"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/go-redis/redis"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/google/go-cloud"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  branch = "release-1.6.4"
  name = "github.com/grpc-ecosystem/grpc-gateway"
  source = "github.com/TheThingsIndustries/grpc-gateway"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/crypto"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "=1.9.1"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "1.3.1"

[[constraint]]
  name = "github.com/robertkrimen/otto"
  source = "github.com/TheThingsIndustries/otto"

[[constraint]]
  branch = "master"
  name = "github.com/smartystreets/assertions"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.18.0"

[[constraint]]
  branch = "master"
  name = "go.thethings.network/lorawan-stack-legacy"
  source = "github.com/TheThingsIndustries/lorawan-stack-legacy"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

[[override]]
  name = "github.com/golang/dep"
  version = "0.5.0"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"
