required = ["github.com/golang/dep"]

[[constraint]]
  name = "github.com/TheThingsNetwork/go-cayenne-lib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/grpc-gateway"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/crypto"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "1.3.0"

[[constraint]]
  name = "github.com/robertkrimen/otto"
  source = "github.com/johanstokking/otto"

[[constraint]]
  branch = "master"
  name = "github.com/smartystreets/assertions"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.14.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[override]]
  name = "github.com/golang/dep"
  version = "0.5.0"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"
