extends:
  - ttn
  - plugin:jest/recommended

parser: babel-eslint

plugins:
  - flowtype

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

env:
  node: true
  jest: true

globals:
  shallow: true
  render: true
  mount: true
  snapshotDiff: true

rules:
  jest/no-large-snapshots:
    - warn
    - maxSize: 400

  # Warn on console occurrences
  no-console:
    - warn

  # Warn on missing JsDoc definitions
  valid-jsdoc:
    - warn
    - prefer:
        return: returns
        arg: param
        argument: param
        class: constructor
        virtual: abstract
      preferType:
        String: string
        Object: object
        Function: function
      requireReturn: false
