extends:
  - ttn
  - plugin:jest/recommended
  - prettier
  - prettier/react

parser: babel-eslint

plugins:
  - jsdoc
  - prettier

env:
  node: true
  jest: true

globals:
  shallow: true
  render: true
  mount: true
  snapshotDiff: true

parserOptions:
  ecmaFeatures:
    # Remove after migration
    legacyDecorators: true

rules:
  prettier/prettier: error

  jest/no-large-snapshots:
    - warn
    - maxSize: 400

  # Change to `error` after https://github.com/TheThingsNetwork/lorawan-stack/issues/1086
  # is resolved.

  # Prevent extraneous defaultProps on components
  react/default-props-match-prop-types: warn
  # Enforce a defaultProps definition for every prop that is not a required prop
  react/require-default-props: warn
  # Prevent definitions of unused prop types
  react/no-unused-prop-types: warn
  # Prevent missing props validation in a React component definition
  react/prop-types: warn
  # Enforce propTypes declarations alphabetical sorting
  react/sort-prop-types: warn
  # Prevent vague prop types
  react/forbid-prop-types:
    - warn
    - forbid:
        - any
        - array
        - object
      checkContextTypes: true
      checkChildContextTypes: true

  jsdoc/no-undefined-types: error
  jsdoc/check-param-names: error
  jsdoc/check-types: error
  jsdoc/require-param-name: error
  jsdoc/require-param-type: error
  jsdoc/require-hyphen-before-param-description: error

  # Warn on console occurrences
  no-console:
    - warn

  # Warn on missing JsDoc definitions
  valid-jsdoc:
    - warn
    - prefer:
        return: returns
        arg: param
        argument: param
        class: constructor
        virtual: abstract
      requireReturn: false
