extends: ttn

parser: babel-eslint

plugins:
  - flowtype

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

rules:
  # Warn on missing JsDoc definitions
  valid-jsdoc:
    - warn
    - prefer:
        return: returns
        arg: param
        argument: param
        class: constructor
        virtual: abstract
      preferType:
        String: string
        Object: object
        Function: function
      requireReturn: false

  flowtype/boolean-style:
    - error
    - bool

  flowtype/define-flow-type:
    - warn

  flowtype/delimiter-dangle:
    - error
    - always-multiline

  flowtype/generic-spacing:
    - error
    - never

  flowtype/no-weak-types:
    - off

  flowtype/require-parameter-type:
    - off

  flowtype/require-return-type:
    - off

  flowtype/require-valid-file-annotation:
    - error

  flowtype/semi:
    - error
    - never

  flowtype/space-after-type-colon:
    - error
    - always

  flowtype/space-before-type-colon:
    - error
    - always

  flowtype/space-before-generic-bracket:
    - error
    - never

  flowtype/union-intersection-spacing:
    - error
    - always

  flowtype/use-flow-type:
    - warn

  flowtype/valid-syntax:
    - warn

  # vim: ft=yaml
