<%
  for (var filetype in htmlWebpackPlugin.files) {
    if (['manifest', 'chunks', 'publicPath'].indexOf(filetype) !== -1) continue;
    for (var file of htmlWebpackPlugin.files[filetype]) {
%>"<%= file.replace(/^.*\//,'').replace(/\.[a-f0-9]{20}/,'') %>": "<%= file.replace(/^.*\//,'') %>"
<% }} %>