[params]
  [params.search]
    enabled = false
    apikey = ""
    index = ""
  [params.intercom]
    enabled = false
    appid = ""
  [params.feedback]
    enabled = false
  [params.analytics]
    enabled = false
    trackingid = ""
