name: End-to-end Tests
on:
  pull_request:
    paths:
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - 'pkg/**'
      - 'tools/**'
      - 'config/**'
      - '!config/stack/ttn-lw-stack.yml'
      - 'package.json'
      - 'pkg/webui/**'
      - 'sdk/js/**'
      - 'yarn.lock'
      - 'cypress/**'
      - 'docker-compose.yml'

jobs:
  end-to-end:
    name: Frontend based (cypress)
    runs-on: ubuntu-18.04
    env:
      TTN_LW_LOG_LEVEL: debug
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Initialize public folder cache
        id: public-cache
        uses: actions/cache@v2
        with:
          path: public
          key: public-cache-${{ hashFiles('pkg/webui/**') }}-${{ hashFiles('sdk/js/**/*.js', 'sdk/js/generated/*.json') }}-${{ hashFiles('config/webpack.config.babel.js') }}-${{ hashFiles('yarn.lock', 'sdk/js/yarn.lock')}}
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: '~1.14'
      - name: Initialize Go module cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go tool dependencies
        run: |
          cd tools
          go mod download
      - name: Initialize tool binary cache
        uses: actions/cache@v2
        with:
          path: tools/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
      - name: Make Mage
        run: make tools/bin/mage
      - name: Initialize stack environment
        run: tools/bin/mage init
      - name: Run test preparations
        run: tools/bin/mage -v dev:dbStop dev:dbErase dev:dbStart dev:initStack dev:sqlDump
      - name: Build frontend
        if: steps.public-cache.outputs.cache-hit != 'true'
        run: tools/bin/mage js:build
      - name: Run frontend end-to-end tests
        run: tools/bin/mage dev:startDevStack & tools/bin/mage -v js:cypressHeadless
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: .cache/devStack.log
      - name: Upload screenshots for failed tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
